version: '3.7'
services:
    conda-learn:
        build: ./source/conda-learn
#        image: continuumio/anaconda3
        container_name: condaL
        command: /bin/bash
        stdin_open: true
        tty: true
        networks:
            - nets
        ports:
            - 9000:8000
        environment:
            - DISPLAY=172.16.2.44:0
        volumes:
            - ${DOCUMENTROOT}:/data/www
        restart: always

# 加入公共服务网络
networks:
  nets:
    external: 
        name: shared_nets
