version: '3.7'
services:
    nodejs:
        image: node:13.2.0-stretch
        container_name: nodejs
        command: /bin/bash
        stdin_open: true
        tty: true
        networks:
            - nets
        ports:
            - 8001:8001
            - 8002:8002
            - 8003:8003
            - 8004:8004
            - 8005:8005
        volumes:
            - ${DOCUMENTROOT}:/data/www
        restart: always

# 加入公共服务网络
networks:
  nets:
    external: false
