version: '3.7'
services:
    redis:
        image: redis:5.0-alpine
        container_name: redis
        networks:
            - nets
        ports:
            - 6379:6379
        volumes:
            - ${DATA_PATH}/redis:/data
        restart: always
    memcached:
        image: memcached:1.5-alpine
        container_name: memcached
        networks:
            - nets
        ports:
            - 11211:11211
        restart: always
    beanstalkd:
        image: schickling/beanstalkd:latest
        container_name: beanstalkd_host
        networks:
            - nets
        ports:
            - 11300:11300
        restart: always
    beanstalkd1:
        image: schickling/beanstalkd:latest
        container_name: beanstalkd1
        networks:
            - nets
        ports:
            - 11301:11300
        restart: always
    beanstalkd2:
        image: schickling/beanstalkd:latest
        container_name: beanstalkd2
        networks:
            - nets
        ports:
            - 11302:11300
        restart: always
    beanstalkd3:
        image: schickling/beanstalkd:latest
        container_name: beanstalkd3
        networks:
            - nets
        ports:
            - 11303:11300
        restart: always
    mongo:
        image: mongo:4.0.6
        container_name: mongo
        networks:
            - nets
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ${DATA_PATH}/mongo:/data/db
            - ${LOG_PATH}/mongo:/var/log/mongodb
        # environment:
        #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    mysql:
        image: mysql:5.7
        container_name: mysql
        networks:
            - nets
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${DATA_PATH}/mysql:/var/lib/mysql
        restart: always
    # elasticsearch:
    #     image: elasticsearch:7.5.0
    #     container_name: elasticsearch
    #     networks:
    #         - nets
    #     ports:
    #         - 9200:9200
    #         - 9300:9300
    #     restart: always
    #     volumes:
    #         - ${DATA_PATH}/elasticsearch:/var/lib/elasticsearch/data
    #         - ${LOG_PATH}/elasticsearch:/var/lib/elasticsearch/logs
    #     environment:
    #         - discovery.type=single-node

#自定义网络
networks:
  nets:
    external: false