version: '3.7'
services:
    composer:
        image: composer:1.9.0
        container_name: composer
        command: /bin/bash
        stdin_open: true
        tty: true
        networks:
            - nets
        volumes:
            - ${DOCUMENTROOT}:/app
        restart: always
    php-fpm:
        build: ./source/php-fpm
        container_name: php-fpm
        networks:
            - nets
        ports:
            - 9000
        volumes:
            - ${DOCUMENTROOT}:/data/www
        restart: always
    nginx:
        image: nginx:1.16.1-alpine
        container_name: nginx
        networks:
            - nets
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php-fpm
        volumes:
            - ${CONF_PATH}/nginx/conf.d:/etc/nginx/conf.d
            - ${CONF_PATH}/nginx/ssl:/etc/nginx/ssl
            - ${LOG_PATH}/nginx:/var/log/nginx/
            # - ${DOCUMENTROOT}:/data/www/
        restart: always

# 加入公共服务网络
networks:
  nets:
    external:
        name: shared_nets