version: '3.7'
services:
    composer:
        image: composer:1.9.0
        container_name: php_composer
        command: /bin/bash
        stdin_open: true
        tty: true
        networks:
            - nets
        volumes:
            - ${DOCUMENTROOT}:/app
        restart: always
    redis:
        image: redis:5.0-alpine
        container_name: php_redis
        networks:
            - nets
        ports:
            - 6379:6379
        volumes:
            - ${DATA_PATH}/redis:/data
        restart: always
    memcached:
        image: memcached:1.5-alpine
        container_name: php_memcached
        networks:
            - nets
        ports:
            - 11211:11211
        restart: always
    beanstalkd:
        image: schickling/beanstalkd:latest
        container_name: beanstalkd_host
        networks:
            - nets
        ports:
            - 11300:11300
        restart: always
    mongo:
        build: ./source/mongo
        container_name: php_mongo
        networks:
            - nets
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ${DATA_PATH}/mongo:/data/db
            - ${LOG_PATH}/mongo:/var/log/mongodb
        environment:
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    mysql:
        image: mysql:5.7
        container_name: php_mysql
        networks:
            - nets
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${DATA_PATH}/mysql:/var/lib/mysql
        restart: always
    php-fpm:
        build: ./source/php-fpm
        container_name: php_php-fpm
        networks:
            - nets
        ports:
            - 9000
        volumes:
            - ${DOCUMENTROOT}:/data/www
        restart: always
    nginx:
        image: nginx:1.16.1-alpine
        container_name: php_nginx
        networks:
            - nets
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php-fpm
        volumes:
            - ${CONF_PATH}/nginx/conf.d:/etc/nginx/conf.d
            - ${CONF_PATH}/nginx/ssl:/etc/nginx/ssl
            - ${LOG_PATH}/nginx:/var/log/nginx/
            - ${DOCUMENTROOT}:/data/www/
        restart: always

#自定义网络
networks:
  nets:
    external: false